x-api-conf: &api-conf
  image: #TODO
  environment:
    CONSUMERS_AMOUNT: 20
    CONSUMERS_CONCURRENCY_FACTOR: 8192
    PAYMENT_PROCESSOR_RESPONSE_TIMEOUT_MS: 4000
    PIPELINE_POLLING_MS: 50
    CONNECTION_ACQUIRE_TIMEOUT_MS: 5000
    MAX_CONNECTIONS: 500
    JAVA_OPTS: >
      -XX:+UseG1GC
      -XX:+AlwaysPreTouch
      -XX:+UseNUMA
      -XX:+UseFastAccessorMethods
      -XX:+UseStringCache
      -XX:+OptimizeStringConcat
      -Dio.netty.allocator.type=pooled
      -Dreactor.schedulers.defaultBoundedElasticQueueSize=200000
      -Dreactor.schedulers.defaultBoundedElasticOnVirtualThreads=true
      -Dreactor.schedulers.defaultBoundedElasticSize=1024
  networks:
    - backend
    - payment-processor
  depends_on:
    key-db:
      condition: service_healthy
  deploy:
    resources:
      limits:
        cpus: "0.45"
        memory: "125MB"

services:
  key-db:
    image: eqalpha/keydb:latest
    ports:
      - "6379:6379"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "20MB"

  api1:
    <<: *api-conf

  api2:
    <<: *api-conf

  haproxy:
    image: haproxy:3.3-dev
    ports:
      - "9999:9999"
    networks:
      - backend
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "80MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true