server:
  port: 9999
spring:
  application:
    name: rinha-backend-2025
http:
  config:
    default-payment-processor:
      base-url: http://payment-processor-default:8080
    fallback-payment-processor:
      base-url: http://payment-processor-fallback:8080
config:
  key-db:
    uri: redis://key-db:6379
    queue:
      pending-registration-payments:
        name: pending-registration-payments
        consumers-amount: ${CONSUMERS_AMOUNT:20}
        consumers-concurrency-factor: ${CONSUMERS_CONCURRENCY_FACTOR:1}
        producer-timeout-ms: ${PRODUCER_TIMEOUT_MS:5000}
      registered-payments:
        name: registered-payments