server:
  port: 8054
spring:
  application:
    name: rinha-backend-2025
logging:
  level:
    reactor:
      netty:
        http-client: off
    io:
      netty: off
http:
  config:
    default-payment-processor:
      base-url: http://payment-processor-default:8080
    fallback-payment-processor:
      base-url: http://payment-processor-fallback:8080
    response-timeout-ms: ${PAYMENT_PROCESSOR_RESPONSE_TIMEOUT_MS:5000}
    max-connections: ${MAX_CONNECTIONS:500}
    connection-acquire-timeout-ms: ${CONNECTION_ACQUIRE_TIMEOUT_MS:5000}
config:
  key-db:
    uri: redis://key-db:6379
    set:
      payments-by-date:
        key:
          default: default-registered-payments:by_date
          fallback: fallback-registered-payments:by_date
    queue:
      pending-registration-payments:
        key: pending-registration-payments
        consumers-amount: ${CONSUMERS_AMOUNT:20}
        consumers-concurrency-factor: ${CONSUMERS_CONCURRENCY_FACTOR:1}
        pipeline-polling-rate-ms: ${PIPELINE_POLLING_MS:100}
        producer-timeout-ms: ${PRODUCER_TIMEOUT_MS:5000}
