name: Publish New Image Version

on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/rinha-backend-2025
  MAVEN_PROFILE: "native"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ linux/amd64, linux/arm64 ]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: | 
            ~/.m2/repository
            target
            ~/.graalvm
            /tmp/graalvm
          key: ${{ runner.os }}-fullcache-${{ hashFiles('**/pom.xml') }}

      - name: Setup Docker Buildx # Step necessário pois contém driver para o cache que escolhi: GHA
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true

      - name: Auth to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker Tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=semver, pattern={{version}}
            type=semver, pattern={{major}}.{{minor}}
            type=ref, event=branch

      - name: Build Native Executable
        run: |
          docker buildx build \
            --target build \
            --tag temp-build-image \
            --load \
            --build-arg MAVEN_PROFILE=${{ env.MAVEN_PROFILE }} \
            .

      - name: Docker Publish
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: ${{ matrix.platform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            MAVEN_PROFILE=${{ env.MAVEN_PROFILE }}

